name: CI (Docker + Tests)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build image from Dockerfile.dev and load it into the local Docker daemon
      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          tags: app-under-test:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

        # Run tests by overriding the image's CMD with the test command
      - name: Run tests
        run: |
          docker run --rm \
            -e CI=true \
            app-under-test:ci \
            npm run test -- --ci --watchAll=false
